### ISSUE TITLE
How are NemSMS'es sent/modelled in the Message Model?

### ISSUE THREAD

**Issue by andersfausboll** [digst/MeMo#65]
We have to clarify:
1) Should NemSMS'es be sent through Digital Post (assumption: yes)
2) How should they be modelled?
    - Option 1: If no MessageBody is included, assume NemSMS
    - Option 2: Add a 'MessageType' attribute to the MessageHeader to specify DPMessage OR NemSMS

**Comment by madsh** [comment]
Decided to put it into a header field. To allow for future encryption off body... but still allow infrastructure to send notification
